name: Update repo

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Update
        run: |
          if [[ -z "${{ inputs.tag }}" ]]; then
            tag=$(curl -s -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/repos/prometheus/prometheus/releases/latest \
              | jq -r '.tag_name')
          else
            tag="${{ inputs.tag }}"
          fi

          if curl --fail -s -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/repos/litetex-oss/prometheus-slim/branches/release-$tag > /dev/null; then
            echo "Branch already exists; Aborting"
            exit 0
          fi

          git clone --branch "$tag" https://github.com/prometheus/prometheus.git

          git config --global user.email "164098849+litetex-oss-bot@users.noreply.github.com"
          git config --global user.name "litetex-oss-bot"
          
          cd prometheus
          git switch -c release-$tag

          rm -rf .github
          git commit -a -m "Deleted .github folder"

          rm -f plugins/plugin_*
          git commit -a -m "Deleted all plugins"
          
          git remote add slim https://litetex-oss-bot:${{ secrets.PUSH_PAT }}@github.com/litetex-oss/prometheus-slim.git
          git push --set-upstream slim -u release-$tag
